USE FitnessClub;
GO

DROP TABLE IF EXISTS Zapis;
DROP TABLE IF EXISTS Zajecia;

DROP TABLE IF EXISTS Czlonek;
DROP TABLE IF EXISTS Instruktor;
DROP TABLE IF EXISTS TypZajec;
DROP TABLE IF EXISTS Sala;
GO